# SPDX-FileCopyrightText: 2025 Mass Labs
#
# SPDX-License-Identifier: MIT

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: base_types.proto
# Protobuf Python Version: 5.29.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 4, "", "base_types.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10\x62\x61se_types.proto\x12\x0bmarket.mass"\x18\n\tRequestId\x12\x0b\n\x03raw\x18\x01 \x01(\x12"\x18\n\tSignature\x12\x0b\n\x03raw\x18\x01 \x01(\x0c"\x18\n\tPublicKey\x12\x0b\n\x03raw\x18\x01 \x01(\x0c"\x16\n\x07Uint256\x12\x0b\n\x03raw\x18\x01 \x01(\x0c"\x17\n\x08ObjectId\x12\x0b\n\x03raw\x18\x01 \x01(\x0c\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "base_types_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_REQUESTID"]._serialized_start = 33
    _globals["_REQUESTID"]._serialized_end = 57
    _globals["_SIGNATURE"]._serialized_start = 59
    _globals["_SIGNATURE"]._serialized_end = 83
    _globals["_PUBLICKEY"]._serialized_start = 85
    _globals["_PUBLICKEY"]._serialized_end = 109
    _globals["_UINT256"]._serialized_start = 111
    _globals["_UINT256"]._serialized_end = 133
    _globals["_OBJECTID"]._serialized_start = 135
    _globals["_OBJECTID"]._serialized_end = 158
# @@protoc_insertion_point(module_scope)
