# SPDX-FileCopyrightText: 2025 Mass Labs
#
# SPDX-License-Identifier: MIT

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: error.proto
# Protobuf Python Version: 5.29.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 4, "", "error.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0b\x65rror.proto\x12\x0bmarket.mass"\xa0\x01\n\x05\x45rror\x12%\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x17.market.mass.ErrorCodes\x12\x0f\n\x07message\x18\x02 \x01(\t\x12:\n\x0f\x61\x64\x64itional_info\x18\x03 \x01(\x0b\x32!.market.mass.Error.AdditionalInfo\x1a#\n\x0e\x41\x64\x64itionalInfo\x12\x11\n\tobject_id\x18\x01 \x01(\x04*\xa4\x03\n\nErrorCodes\x12\x1b\n\x17\x45RROR_CODES_UNSPECIFIED\x10\x00\x12\x19\n\x15\x45RROR_CODES_NOT_FOUND\x10\x01\x12\x17\n\x13\x45RROR_CODES_INVALID\x10\x02\x12!\n\x1d\x45RROR_CODES_NOT_AUTHENTICATED\x10\x03\x12%\n!ERROR_CODES_ALREADY_AUTHENTICATED\x10\x04\x12!\n\x1d\x45RROR_CODES_ALREADY_CONNECTED\x10\x05\x12,\n(ERROR_CODES_TOO_MANY_CONCURRENT_REQUESTS\x10\x06\x12 \n\x1c\x45RROR_CODES_UNLINKED_KEYCARD\x10\x07\x12+\n\'ERROR_CODES_MINIMUM_VERSION_NOT_REACHED\x10\x08\x12\x1c\n\x18\x45RROR_CODES_OUT_OF_STOCK\x10\t\x12\x19\n\x15\x45RROR_CODES_SIMULATED\x10\n\x12"\n\x1e\x45RROR_CODES_CLOSE_SUBSCRIPTION\x10\x0b\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "error_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ERRORCODES"]._serialized_start = 192
    _globals["_ERRORCODES"]._serialized_end = 612
    _globals["_ERROR"]._serialized_start = 29
    _globals["_ERROR"]._serialized_end = 189
    _globals["_ERROR_ADDITIONALINFO"]._serialized_start = 154
    _globals["_ERROR_ADDITIONALINFO"]._serialized_end = 189
# @@protoc_insertion_point(module_scope)
