# SPDX-FileCopyrightText: 2025 Mass Labs
#
# SPDX-License-Identifier: MIT

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: storage.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 28, 3, "", "storage.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()
from massmarket import base_types_pb2 as base__types__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\rstorage.proto\x12\x0bmarket.mass\x1a\x10\x62\x61se_types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe9\x06\n\x05Order\x12!\n\x02id\x18\x01 \x01(\x0b\x32\x15.market.mass.ObjectId\x12'\n\x05items\x18\x02 \x03(\x0b\x32\x18.market.mass.OrderedItem\x12\x17\n\x0fshipping_status\x18\x03 \x01(\t\x12\x34\n\x0b\x63\x61nceled_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x88\x01\x01\x12\x34\n\x0b\x63ommited_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x01\x88\x01\x01\x12\x39\n\x0finvoice_address\x18\x06 \x01(\x0b\x32\x1b.market.mass.AddressDetailsH\x02\x88\x01\x01\x12:\n\x10shipping_address\x18\x07 \x01(\x0b\x32\x1b.market.mass.AddressDetailsH\x03\x88\x01\x01\x12;\n\x12\x61\x64\x64ress_updated_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x04\x88\x01\x01\x12-\n\x0c\x63hosen_payee\x18\t \x01(\x0b\x32\x12.market.mass.PayeeH\x05\x88\x01\x01\x12\x37\n\x0f\x63hosen_currency\x18\n \x01(\x0b\x32\x19.market.mass.ShopCurrencyH\x06\x88\x01\x01\x12\x39\n\x0fpayment_details\x18\x0b \x01(\x0b\x32\x1b.market.mass.PaymentDetailsH\x07\x88\x01\x01\x12\x43\n\x1apayment_details_created_at\x18\x0c \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x08\x88\x01\x01\x12;\n\x14payment_transactions\x18\r \x03(\x0b\x32\x1d.market.mass.OrderTransactionB\x0e\n\x0c_canceled_atB\x0e\n\x0c_commited_atB\x12\n\x10_invoice_addressB\x13\n\x11_shipping_addressB\x15\n\x13_address_updated_atB\x0f\n\r_chosen_payeeB\x12\n\x10_chosen_currencyB\x12\n\x10_payment_detailsB\x1d\n\x1b_payment_details_created_atb\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "storage_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ORDER"]._serialized_start = 82
    _globals["_ORDER"]._serialized_end = 955
# @@protoc_insertion_point(module_scope)
