# SPDX-FileCopyrightText: 2025 Mass Labs
#
# SPDX-License-Identifier: MIT

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: subscription.proto
# Protobuf Python Version: 5.29.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 4, "", "subscription.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()
from massmarket import base_types_pb2 as base__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12subscription.proto\x12\x0bmarket.mass\x1a\x10\x62\x61se_types.proto"\x86\x02\n\x13SubscriptionRequest\x12\x19\n\x11start_shop_seq_no\x18\x01 \x01(\x04\x12%\n\x07shop_id\x18\x02 \x01(\x0b\x32\x14.market.mass.Uint256\x12\x38\n\x07\x66ilters\x18\x03 \x03(\x0b\x32\'.market.mass.SubscriptionRequest.Filter\x1as\n\x06\x46ilter\x12,\n\x0bobject_type\x18\x03 \x01(\x0e\x32\x17.market.mass.ObjectType\x12-\n\tobject_id\x18\x04 \x01(\x0b\x32\x15.market.mass.ObjectIdH\x00\x88\x01\x01\x42\x0c\n\n_object_id"\x8f\x02\n\x17SubscriptionPushRequest\x12\x17\n\x0fsubscription_id\x18\x01 \x01(\x0c\x12K\n\x04sets\x18\x02 \x03(\x0b\x32=.market.mass.SubscriptionPushRequest.SequencedPartialPatchSet\x1a\x8d\x01\n\x18SequencedPartialPatchSet\x12\x13\n\x0bshop_seq_no\x18\x01 \x01(\x04\x12\x18\n\x10patch_leaf_index\x18\x02 \x01(\r\x12\x0e\n\x06header\x18\x03 \x01(\x0c\x12\x11\n\tsignature\x18\x04 \x01(\x0c\x12\x0f\n\x07patches\x18\x05 \x03(\x0c\x12\x0e\n\x06proofs\x18\x06 \x03(\x0c"4\n\x19SubscriptionCancelRequest\x12\x17\n\x0fsubscription_id\x18\x01 \x01(\x0c*\xbc\x01\n\nObjectType\x12\x1b\n\x17OBJECT_TYPE_UNSPECIFIED\x10\x00\x12\x17\n\x13OBJECT_TYPE_LISTING\x10\x01\x12\x13\n\x0fOBJECT_TYPE_TAG\x10\x02\x12\x15\n\x11OBJECT_TYPE_ORDER\x10\x03\x12\x17\n\x13OBJECT_TYPE_ACCOUNT\x10\x04\x12\x18\n\x14OBJECT_TYPE_MANIFEST\x10\x05\x12\x19\n\x15OBJECT_TYPE_INVENTORY\x10\x06\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "subscription_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_OBJECTTYPE"]._serialized_start = 647
    _globals["_OBJECTTYPE"]._serialized_end = 835
    _globals["_SUBSCRIPTIONREQUEST"]._serialized_start = 54
    _globals["_SUBSCRIPTIONREQUEST"]._serialized_end = 316
    _globals["_SUBSCRIPTIONREQUEST_FILTER"]._serialized_start = 201
    _globals["_SUBSCRIPTIONREQUEST_FILTER"]._serialized_end = 316
    _globals["_SUBSCRIPTIONPUSHREQUEST"]._serialized_start = 319
    _globals["_SUBSCRIPTIONPUSHREQUEST"]._serialized_end = 590
    _globals["_SUBSCRIPTIONPUSHREQUEST_SEQUENCEDPARTIALPATCHSET"]._serialized_start = (
        449
    )
    _globals["_SUBSCRIPTIONPUSHREQUEST_SEQUENCEDPARTIALPATCHSET"]._serialized_end = 590
    _globals["_SUBSCRIPTIONCANCELREQUEST"]._serialized_start = 592
    _globals["_SUBSCRIPTIONCANCELREQUEST"]._serialized_end = 644
# @@protoc_insertion_point(module_scope)
