# SPDX-FileCopyrightText: 2025 Mass Labs
#
# SPDX-License-Identifier: MIT

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport.proto
# Protobuf Python Version: 5.29.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 4, "", "transport.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0ftransport.proto\x12\x0bmarket.mass")\n\x14PatchSetWriteRequest\x12\x11\n\tpatch_set\x18\x01 \x01(\x0c"F\n\x11SyncStatusRequest\x12\x17\n\x0fsubscription_id\x18\x01 \x01(\x04\x12\x18\n\x10unpushed_patches\x18\x02 \x01(\x04"\r\n\x0bPingRequestb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "transport_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_PATCHSETWRITEREQUEST"]._serialized_start = 32
    _globals["_PATCHSETWRITEREQUEST"]._serialized_end = 73
    _globals["_SYNCSTATUSREQUEST"]._serialized_start = 75
    _globals["_SYNCSTATUSREQUEST"]._serialized_end = 145
    _globals["_PINGREQUEST"]._serialized_start = 147
    _globals["_PINGREQUEST"]._serialized_end = 160
# @@protoc_insertion_point(module_scope)
