schema = 3

[mod]
  [mod."github.com/bits-and-blooms/bitset"]
    version = "v1.13.0"
    hash = "sha256-1jccFEH9In72Jt3wSn4vi4/MJd/UDfDrC9DlmsGVc9o="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.3.0"
    hash = "sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY="
  [mod."github.com/consensys/bavard"]
    version = "v0.1.13"
    hash = "sha256-DEx0JuvgqNCNv7IMHlbLJK6pb1ru29C/rTSKh6YksVg="
  [mod."github.com/consensys/gnark-crypto"]
    version = "v0.12.1"
    hash = "sha256-M7S5XbXKsvx2Uw2qNtsQg0RmlhFtSCzXEL2T3vzeq7o="
  [mod."github.com/crate-crypto/go-ipa"]
    version = "v0.0.0-20240223125850-b1e8a79f509c"
    hash = "sha256-FxggqFBZSulCK2courdECyPCdNFtSOscl76Mhj3hAxU="
  [mod."github.com/crate-crypto/go-kzg-4844"]
    version = "v1.0.0"
    hash = "sha256-j9Rxv+ERT8NhSbPgVBhb4KGb+HhpHGiymt8yj9ZKWgk="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/decred/dcrd/dcrec/secp256k1/v4"]
    version = "v4.0.1"
    hash = "sha256-JBVRp40dDj0puapoQloV13H6TMjgJiypzYojcDRE2jI="
  [mod."github.com/ethereum/c-kzg-4844"]
    version = "v1.0.0"
    hash = "sha256-jyqnqoZ3Ogpi5M7778F3ferfYFqR9vEaRESTakhb8Yw="
  [mod."github.com/ethereum/go-ethereum"]
    version = "v1.14.12"
    hash = "sha256-GZWvZcQXAg3EoVTvf+W60g9boa5MOsEfFHw1ZVl0reE="
  [mod."github.com/ethereum/go-verkle"]
    version = "v0.1.1-0.20240829091221-dffa7562dbe9"
    hash = "sha256-C8JxZTUEHy7y0Cg3cRmA0RInEoA/JLIxlnOa1Y/DnVU="
  [mod."github.com/fxamacker/cbor/v2"]
    version = "v2.7.0"
    hash = "sha256-ln5ms4UxxQ563bZ2UaNLG/bNsmohlgK18K+UUOyZNA0="
  [mod."github.com/gabriel-vasile/mimetype"]
    version = "v1.4.8"
    hash = "sha256-ElqfQtnoGHyVqtN0mJjeWakQ6N5x+nVaX3+uOV7Q5Xk="
  [mod."github.com/go-playground/locales"]
    version = "v0.14.1"
    hash = "sha256-BMJGAexq96waZn60DJXZfByRHb8zA/JP/i6f/YrW9oQ="
  [mod."github.com/go-playground/universal-translator"]
    version = "v0.18.1"
    hash = "sha256-2/B2qP51zfiY+k8G0w0D03KXUc7XpWj6wKY7NjNP/9E="
  [mod."github.com/go-playground/validator/v10"]
    version = "v10.23.0"
    hash = "sha256-vzLoqM9L248OFLZq4NVqnrKXOhNM2bSlqzW6g78BObs="
  [mod."github.com/holiman/uint256"]
    version = "v1.3.1"
    hash = "sha256-Mx2kd5H0sph6Nq8hI55nEn31saXvmg3df7hb/t8bHrQ="
  [mod."github.com/huandu/go-clone"]
    version = "v1.7.2"
    hash = "sha256-NbnxF80nH403a+qX/KLJGzNWhrgtMRy32WnzD3HMfY0="
  [mod."github.com/huandu/go-clone/generic"]
    version = "v1.7.2"
    hash = "sha256-ZD8VFQf2CM/NZRA7OfiDEd3w1LgHuwlvx0kvH5DAwkg="
  [mod."github.com/ipfs/go-cid"]
    version = "v0.4.1"
    hash = "sha256-QygRTLQBk8tPQVs3k1m5koinkZtTRKWyakJCDV4rzT0="
  [mod."github.com/klauspost/cpuid/v2"]
    version = "v2.2.9"
    hash = "sha256-6UnDBLqlTsKVeZNl5snKQiEBb8xGK5yyg2eZBg7QHLs="
  [mod."github.com/kr/pretty"]
    version = "v0.3.1"
    hash = "sha256-DlER7XM+xiaLjvebcIPiB12oVNjyZHuJHoRGITzzpKU="
  [mod."github.com/leodido/go-urn"]
    version = "v1.4.0"
    hash = "sha256-Q6kplWkY37Tzy6GOme3Wut40jFK4Izun+ij/BJvcEu0="
  [mod."github.com/minio/sha256-simd"]
    version = "v1.0.1"
    hash = "sha256-4hfGDIQaWq8fvtGzHDhoK9v2IocXnJY7OAL6saMJbmA="
  [mod."github.com/mmcloughlin/addchain"]
    version = "v0.4.0"
    hash = "sha256-zSWSSUElCVFH5mydFlF2mzn4Wsm1WHASRxQ5TKa+To8="
  [mod."github.com/mr-tron/base58"]
    version = "v1.2.0"
    hash = "sha256-8FzMu3kHUbBX10pUdtGf59Ag7BNupx8ZHeUaodR1/Vk="
  [mod."github.com/multiformats/go-base32"]
    version = "v0.1.0"
    hash = "sha256-O2IM7FB+Y9MkDdZztyQL5F8oEnmON2Yew7XkotQziio="
  [mod."github.com/multiformats/go-base36"]
    version = "v0.2.0"
    hash = "sha256-GKNnAGA0Lb39BDGYBm1ieKdXmho8Pu7ouyfVPXvV0PE="
  [mod."github.com/multiformats/go-multibase"]
    version = "v0.2.0"
    hash = "sha256-w+hp6u5bWyd34qe0CX+bq487ADqq6SgRR/JuqRB578s="
  [mod."github.com/multiformats/go-multihash"]
    version = "v0.2.3"
    hash = "sha256-zqIIE5jMFzm+qhUrouSF+WdXGeHUEYIQvVnKWWU6mRs="
  [mod."github.com/multiformats/go-varint"]
    version = "v0.0.7"
    hash = "sha256-To3Uuv7uSUJEr5OTwxE1LEIpA62xY3M/KKMNlscHmlA="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/spaolacci/murmur3"]
    version = "v1.1.0"
    hash = "sha256-RWD4PPrlAsZZ8Xy356MBxpj+/NZI7w2XOU14Ob7/Y9M="
  [mod."github.com/stretchr/testify"]
    version = "v1.9.0"
    hash = "sha256-uUp/On+1nK+lARkTVtb5RxlW15zxtw2kaAFuIASA+J0="
  [mod."github.com/supranational/blst"]
    version = "v0.3.13"
    hash = "sha256-VrhbZyotNgVubxSFJH+KH2KOpApGz1PHgC0NFDmqRF0="
  [mod."github.com/x448/float16"]
    version = "v0.8.4"
    hash = "sha256-VKzMTMS9pIB/cwe17xPftCSK9Mf4Y6EuBEJlB4by5mE="
  [mod."golang.org/x/crypto"]
    version = "v0.31.0"
    hash = "sha256-ZBjoG7ZOuTEmjaXPP9txAvjAjC46DeaLs0zrNzi8EQw="
  [mod."golang.org/x/net"]
    version = "v0.33.0"
    hash = "sha256-9swkU9vp6IflUUqAzK+y8PytSmrKLuryidP3RmRfe0w="
  [mod."golang.org/x/sync"]
    version = "v0.10.0"
    hash = "sha256-HWruKClrdoBKVdxKCyoazxeQV4dIYLdkHekQvx275/o="
  [mod."golang.org/x/sys"]
    version = "v0.29.0"
    hash = "sha256-qfsodJQ1H1CBI8yQWOvsXJgY5qHmiuw566HrrIseYHI="
  [mod."golang.org/x/text"]
    version = "v0.21.0"
    hash = "sha256-QaMwddBRnoS2mv9Y86eVC2x2wx/GZ7kr2zAJvwDeCPc="
  [mod."gopkg.in/check.v1"]
    version = "v1.0.0-20201130134442-10cb98267c6c"
    hash = "sha256-VlIpM2r/OD+kkyItn6vW35dyc0rtkJufA93rjFyzncs="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."lukechampine.com/blake3"]
    version = "v1.3.0"
    hash = "sha256-H7ljr3coQkiNKPvn1fWm7wADu/n/PhBefTKn8UF1Wkg="
  [mod."rsc.io/tmplfunc"]
    version = "v0.0.3"
    hash = "sha256-Kii+7DxaSzzn2NphVcEk0W42TXMBFINtm3+B2t7e0cc="
