schema = 4
vendorModulesTxt = "# github.com/bits-and-blooms/bitset v1.13.0\n## explicit; go 1.16\ngithub.com/bits-and-blooms/bitset\n# github.com/cespare/xxhash/v2 v2.3.0\n## explicit; go 1.11\ngithub.com/cespare/xxhash/v2\n# github.com/consensys/bavard v0.1.13\n## explicit; go 1.15\ngithub.com/consensys/bavard\n# github.com/consensys/gnark-crypto v0.12.1\n## explicit; go 1.18\ngithub.com/consensys/gnark-crypto/ecc\ngithub.com/consensys/gnark-crypto/ecc/bls12-381\ngithub.com/consensys/gnark-crypto/ecc/bls12-381/bandersnatch\ngithub.com/consensys/gnark-crypto/ecc/bls12-381/fp\ngithub.com/consensys/gnark-crypto/ecc/bls12-381/fr\ngithub.com/consensys/gnark-crypto/ecc/bls12-381/internal/fptower\ngithub.com/consensys/gnark-crypto/field/generator/config\ngithub.com/consensys/gnark-crypto/field/generator/internal/addchain\ngithub.com/consensys/gnark-crypto/field/hash\ngithub.com/consensys/gnark-crypto/field/pool\ngithub.com/consensys/gnark-crypto/internal/generator/config\ngithub.com/consensys/gnark-crypto/internal/parallel\n# github.com/crate-crypto/go-ipa v0.0.0-20240223125850-b1e8a79f509c\n## explicit; go 1.18\ngithub.com/crate-crypto/go-ipa\ngithub.com/crate-crypto/go-ipa/bandersnatch\ngithub.com/crate-crypto/go-ipa/bandersnatch/fp\ngithub.com/crate-crypto/go-ipa/bandersnatch/fr\ngithub.com/crate-crypto/go-ipa/banderwagon\ngithub.com/crate-crypto/go-ipa/common\ngithub.com/crate-crypto/go-ipa/common/parallel\ngithub.com/crate-crypto/go-ipa/ipa\n# github.com/crate-crypto/go-kzg-4844 v1.0.0\n## explicit; go 1.20\ngithub.com/crate-crypto/go-kzg-4844\ngithub.com/crate-crypto/go-kzg-4844/internal/kzg\ngithub.com/crate-crypto/go-kzg-4844/internal/multiexp\ngithub.com/crate-crypto/go-kzg-4844/internal/utils\n# github.com/datatrails/go-datatrails-merklelog/mmr v0.1.1\n## explicit; go 1.22\ngithub.com/datatrails/go-datatrails-merklelog/mmr\n# github.com/davecgh/go-spew v1.1.1\n## explicit\ngithub.com/davecgh/go-spew/spew\n# github.com/decred/dcrd/dcrec/secp256k1/v4 v4.0.1\n## explicit; go 1.16\ngithub.com/decred/dcrd/dcrec/secp256k1/v4\ngithub.com/decred/dcrd/dcrec/secp256k1/v4/ecdsa\n# github.com/ethereum/c-kzg-4844 v1.0.0\n## explicit; go 1.19\ngithub.com/ethereum/c-kzg-4844/bindings/go\n# github.com/ethereum/go-ethereum v1.14.12\n## explicit; go 1.22\ngithub.com/ethereum/go-ethereum\ngithub.com/ethereum/go-ethereum/accounts\ngithub.com/ethereum/go-ethereum/common\ngithub.com/ethereum/go-ethereum/common/hexutil\ngithub.com/ethereum/go-ethereum/common/math\ngithub.com/ethereum/go-ethereum/common/mclock\ngithub.com/ethereum/go-ethereum/core/types\ngithub.com/ethereum/go-ethereum/crypto\ngithub.com/ethereum/go-ethereum/crypto/kzg4844\ngithub.com/ethereum/go-ethereum/crypto/secp256k1\ngithub.com/ethereum/go-ethereum/crypto/secp256k1/libsecp256k1/include\ngithub.com/ethereum/go-ethereum/crypto/secp256k1/libsecp256k1/src\ngithub.com/ethereum/go-ethereum/crypto/secp256k1/libsecp256k1/src/modules/recovery\ngithub.com/ethereum/go-ethereum/event\ngithub.com/ethereum/go-ethereum/log\ngithub.com/ethereum/go-ethereum/params\ngithub.com/ethereum/go-ethereum/params/forks\ngithub.com/ethereum/go-ethereum/rlp\ngithub.com/ethereum/go-ethereum/rlp/internal/rlpstruct\n# github.com/ethereum/go-verkle v0.1.1-0.20240829091221-dffa7562dbe9\n## explicit; go 1.22\ngithub.com/ethereum/go-verkle\n# github.com/fxamacker/cbor/v2 v2.7.0\n## explicit; go 1.17\ngithub.com/fxamacker/cbor/v2\n# github.com/gabriel-vasile/mimetype v1.4.8\n## explicit; go 1.20\ngithub.com/gabriel-vasile/mimetype\ngithub.com/gabriel-vasile/mimetype/internal/charset\ngithub.com/gabriel-vasile/mimetype/internal/json\ngithub.com/gabriel-vasile/mimetype/internal/magic\n# github.com/go-playground/locales v0.14.1\n## explicit; go 1.17\ngithub.com/go-playground/locales\ngithub.com/go-playground/locales/currency\n# github.com/go-playground/universal-translator v0.18.1\n## explicit; go 1.18\ngithub.com/go-playground/universal-translator\n# github.com/go-playground/validator/v10 v10.24.0\n## explicit; go 1.20\ngithub.com/go-playground/validator/v10\ngithub.com/go-playground/validator/v10/non-standard/validators\n# github.com/holiman/uint256 v1.3.2\n## explicit; go 1.19\ngithub.com/holiman/uint256\n# github.com/huandu/go-clone v1.7.2\n## explicit; go 1.13\ngithub.com/huandu/go-clone\n# github.com/huandu/go-clone/generic v1.7.2\n## explicit; go 1.18\ngithub.com/huandu/go-clone/generic\n# github.com/ipfs/go-cid v0.5.0\n## explicit; go 1.22\ngithub.com/ipfs/go-cid\n# github.com/jackc/pgpassfile v1.0.0\n## explicit; go 1.12\ngithub.com/jackc/pgpassfile\n# github.com/jackc/pgservicefile v0.0.0-20240606120523-5a60cdf6a761\n## explicit; go 1.14\ngithub.com/jackc/pgservicefile\n# github.com/jackc/pgx/v5 v5.7.2\n## explicit; go 1.21\ngithub.com/jackc/pgx/v5\ngithub.com/jackc/pgx/v5/internal/iobufpool\ngithub.com/jackc/pgx/v5/internal/pgio\ngithub.com/jackc/pgx/v5/internal/sanitize\ngithub.com/jackc/pgx/v5/internal/stmtcache\ngithub.com/jackc/pgx/v5/pgconn\ngithub.com/jackc/pgx/v5/pgconn/ctxwatch\ngithub.com/jackc/pgx/v5/pgconn/internal/bgreader\ngithub.com/jackc/pgx/v5/pgproto3\ngithub.com/jackc/pgx/v5/pgtype\n# github.com/klauspost/cpuid/v2 v2.2.9\n## explicit; go 1.20\ngithub.com/klauspost/cpuid/v2\n# github.com/leodido/go-urn v1.4.0\n## explicit; go 1.18\ngithub.com/leodido/go-urn\ngithub.com/leodido/go-urn/scim/schema\n# github.com/masslbs/go-pgmmr v0.0.0-20250206120136-b5495a477745\n## explicit; go 1.23.4\ngithub.com/masslbs/go-pgmmr\n# github.com/minio/sha256-simd v1.0.1\n## explicit; go 1.17\ngithub.com/minio/sha256-simd\n# github.com/mmcloughlin/addchain v0.4.0\n## explicit; go 1.16\ngithub.com/mmcloughlin/addchain\ngithub.com/mmcloughlin/addchain/acc\ngithub.com/mmcloughlin/addchain/acc/ast\ngithub.com/mmcloughlin/addchain/acc/ir\ngithub.com/mmcloughlin/addchain/acc/parse\ngithub.com/mmcloughlin/addchain/acc/parse/internal/parser\ngithub.com/mmcloughlin/addchain/acc/pass\ngithub.com/mmcloughlin/addchain/acc/printer\ngithub.com/mmcloughlin/addchain/alg\ngithub.com/mmcloughlin/addchain/alg/contfrac\ngithub.com/mmcloughlin/addchain/alg/dict\ngithub.com/mmcloughlin/addchain/alg/ensemble\ngithub.com/mmcloughlin/addchain/alg/exec\ngithub.com/mmcloughlin/addchain/alg/heuristic\ngithub.com/mmcloughlin/addchain/alg/opt\ngithub.com/mmcloughlin/addchain/internal/bigint\ngithub.com/mmcloughlin/addchain/internal/bigints\ngithub.com/mmcloughlin/addchain/internal/bigvector\ngithub.com/mmcloughlin/addchain/internal/container/heap\ngithub.com/mmcloughlin/addchain/internal/errutil\ngithub.com/mmcloughlin/addchain/internal/print\ngithub.com/mmcloughlin/addchain/meta\n# github.com/mr-tron/base58 v1.2.0\n## explicit; go 1.12\ngithub.com/mr-tron/base58/base58\n# github.com/multiformats/go-base32 v0.1.0\n## explicit; go 1.18\ngithub.com/multiformats/go-base32\n# github.com/multiformats/go-base36 v0.2.0\n## explicit; go 1.18\ngithub.com/multiformats/go-base36\n# github.com/multiformats/go-multibase v0.2.0\n## explicit; go 1.19\ngithub.com/multiformats/go-multibase\n# github.com/multiformats/go-multihash v0.2.3\n## explicit; go 1.19\ngithub.com/multiformats/go-multihash\ngithub.com/multiformats/go-multihash/core\ngithub.com/multiformats/go-multihash/register/all\ngithub.com/multiformats/go-multihash/register/blake2\ngithub.com/multiformats/go-multihash/register/blake3\ngithub.com/multiformats/go-multihash/register/miniosha256\ngithub.com/multiformats/go-multihash/register/murmur3\ngithub.com/multiformats/go-multihash/register/sha256\ngithub.com/multiformats/go-multihash/register/sha3\n# github.com/multiformats/go-varint v0.0.7\n## explicit; go 1.18\ngithub.com/multiformats/go-varint\n# github.com/pmezard/go-difflib v1.0.0\n## explicit\ngithub.com/pmezard/go-difflib/difflib\n# github.com/spaolacci/murmur3 v1.1.0\n## explicit\ngithub.com/spaolacci/murmur3\n# github.com/stretchr/testify v1.9.0\n## explicit; go 1.17\ngithub.com/stretchr/testify/assert\ngithub.com/stretchr/testify/require\n# github.com/supranational/blst v0.3.13\n## explicit; go 1.11\ngithub.com/supranational/blst/bindings/go\n# github.com/x448/float16 v0.8.4\n## explicit; go 1.11\ngithub.com/x448/float16\n# golang.org/x/crypto v0.32.0\n## explicit; go 1.20\ngolang.org/x/crypto/blake2b\ngolang.org/x/crypto/blake2s\ngolang.org/x/crypto/pbkdf2\ngolang.org/x/crypto/sha3\n# golang.org/x/net v0.34.0\n## explicit; go 1.18\ngolang.org/x/net/html\ngolang.org/x/net/html/atom\n# golang.org/x/sync v0.11.0\n## explicit; go 1.18\ngolang.org/x/sync/errgroup\n# golang.org/x/sys v0.29.0\n## explicit; go 1.18\ngolang.org/x/sys/cpu\ngolang.org/x/sys/unix\n# golang.org/x/text v0.22.0\n## explicit; go 1.18\ngolang.org/x/text/cases\ngolang.org/x/text/internal\ngolang.org/x/text/internal/language\ngolang.org/x/text/internal/language/compact\ngolang.org/x/text/internal/tag\ngolang.org/x/text/language\ngolang.org/x/text/runes\ngolang.org/x/text/secure/bidirule\ngolang.org/x/text/secure/precis\ngolang.org/x/text/transform\ngolang.org/x/text/unicode/bidi\ngolang.org/x/text/unicode/norm\ngolang.org/x/text/width\n# google.golang.org/protobuf v1.34.2\n## explicit; go 1.20\ngoogle.golang.org/protobuf/encoding/prototext\ngoogle.golang.org/protobuf/encoding/protowire\ngoogle.golang.org/protobuf/internal/descfmt\ngoogle.golang.org/protobuf/internal/descopts\ngoogle.golang.org/protobuf/internal/detrand\ngoogle.golang.org/protobuf/internal/editiondefaults\ngoogle.golang.org/protobuf/internal/encoding/defval\ngoogle.golang.org/protobuf/internal/encoding/messageset\ngoogle.golang.org/protobuf/internal/encoding/tag\ngoogle.golang.org/protobuf/internal/encoding/text\ngoogle.golang.org/protobuf/internal/errors\ngoogle.golang.org/protobuf/internal/filedesc\ngoogle.golang.org/protobuf/internal/filetype\ngoogle.golang.org/protobuf/internal/flags\ngoogle.golang.org/protobuf/internal/genid\ngoogle.golang.org/protobuf/internal/impl\ngoogle.golang.org/protobuf/internal/order\ngoogle.golang.org/protobuf/internal/pragma\ngoogle.golang.org/protobuf/internal/set\ngoogle.golang.org/protobuf/internal/strs\ngoogle.golang.org/protobuf/internal/version\ngoogle.golang.org/protobuf/proto\ngoogle.golang.org/protobuf/reflect/protoreflect\ngoogle.golang.org/protobuf/reflect/protoregistry\ngoogle.golang.org/protobuf/runtime/protoiface\ngoogle.golang.org/protobuf/runtime/protoimpl\n# gopkg.in/yaml.v3 v3.0.1\n## explicit\ngopkg.in/yaml.v3\n# lukechampine.com/blake3 v1.3.0\n## explicit; go 1.17\nlukechampine.com/blake3\nlukechampine.com/blake3/bao\nlukechampine.com/blake3/guts\n# rsc.io/tmplfunc v0.0.3\n## explicit; go 1.17\nrsc.io/tmplfunc\nrsc.io/tmplfunc/internal/parse\n"

[mod]
  [mod."github.com/bits-and-blooms/bitset"]
    version = "v1.13.0"
    hash = "sha256-1jccFEH9In72Jt3wSn4vi4/MJd/UDfDrC9DlmsGVc9o="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.3.0"
    hash = "sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY="
  [mod."github.com/consensys/bavard"]
    version = "v0.1.13"
    hash = "sha256-DEx0JuvgqNCNv7IMHlbLJK6pb1ru29C/rTSKh6YksVg="
  [mod."github.com/consensys/gnark-crypto"]
    version = "v0.12.1"
    hash = "sha256-M7S5XbXKsvx2Uw2qNtsQg0RmlhFtSCzXEL2T3vzeq7o="
  [mod."github.com/crate-crypto/go-ipa"]
    version = "v0.0.0-20240223125850-b1e8a79f509c"
    hash = "sha256-FxggqFBZSulCK2courdECyPCdNFtSOscl76Mhj3hAxU="
  [mod."github.com/crate-crypto/go-kzg-4844"]
    version = "v1.0.0"
    hash = "sha256-j9Rxv+ERT8NhSbPgVBhb4KGb+HhpHGiymt8yj9ZKWgk="
  [mod."github.com/datatrails/go-datatrails-merklelog/mmr"]
    version = "v0.1.1"
    hash = "sha256-UuBpi3zAKwlLD5jF1aDqGOhkNy52NRIrRDbeNL99Z7o="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/decred/dcrd/dcrec/secp256k1/v4"]
    version = "v4.0.1"
    hash = "sha256-JBVRp40dDj0puapoQloV13H6TMjgJiypzYojcDRE2jI="
  [mod."github.com/ethereum/c-kzg-4844"]
    version = "v1.0.0"
    hash = "sha256-jyqnqoZ3Ogpi5M7778F3ferfYFqR9vEaRESTakhb8Yw="
  [mod."github.com/ethereum/go-ethereum"]
    version = "v1.14.12"
    hash = "sha256-GZWvZcQXAg3EoVTvf+W60g9boa5MOsEfFHw1ZVl0reE="
  [mod."github.com/ethereum/go-verkle"]
    version = "v0.1.1-0.20240829091221-dffa7562dbe9"
    hash = "sha256-C8JxZTUEHy7y0Cg3cRmA0RInEoA/JLIxlnOa1Y/DnVU="
  [mod."github.com/fxamacker/cbor/v2"]
    version = "v2.7.0"
    hash = "sha256-ln5ms4UxxQ563bZ2UaNLG/bNsmohlgK18K+UUOyZNA0="
  [mod."github.com/gabriel-vasile/mimetype"]
    version = "v1.4.8"
    hash = "sha256-ElqfQtnoGHyVqtN0mJjeWakQ6N5x+nVaX3+uOV7Q5Xk="
  [mod."github.com/go-playground/locales"]
    version = "v0.14.1"
    hash = "sha256-BMJGAexq96waZn60DJXZfByRHb8zA/JP/i6f/YrW9oQ="
  [mod."github.com/go-playground/universal-translator"]
    version = "v0.18.1"
    hash = "sha256-2/B2qP51zfiY+k8G0w0D03KXUc7XpWj6wKY7NjNP/9E="
  [mod."github.com/go-playground/validator/v10"]
    version = "v10.24.0"
    hash = "sha256-zaZtWTAcn1JncUOGVpLigfJW17wxOzJt9aLOs7mNjSM="
  [mod."github.com/holiman/uint256"]
    version = "v1.3.2"
    hash = "sha256-R5ZNDTQy6ELF5Z6BLK/DeMg1JqEtPkDNfFi9XOKmncY="
  [mod."github.com/huandu/go-clone"]
    version = "v1.7.2"
    hash = "sha256-NbnxF80nH403a+qX/KLJGzNWhrgtMRy32WnzD3HMfY0="
  [mod."github.com/huandu/go-clone/generic"]
    version = "v1.7.2"
    hash = "sha256-ZD8VFQf2CM/NZRA7OfiDEd3w1LgHuwlvx0kvH5DAwkg="
  [mod."github.com/ipfs/go-cid"]
    version = "v0.5.0"
    hash = "sha256-BuZKkcBXrnx7mM1c9SP4LdzZoaAoai9U49vITGrYJQk="
  [mod."github.com/jackc/pgpassfile"]
    version = "v1.0.0"
    hash = "sha256-H0nFbC34/3pZUFnuiQk9W7yvAMh6qJDrqvHp+akBPLM="
  [mod."github.com/jackc/pgservicefile"]
    version = "v0.0.0-20240606120523-5a60cdf6a761"
    hash = "sha256-ETpGsLAA2wcm5xJBayr/mZrCE1YsWbnkbSSX3ptrFn0="
  [mod."github.com/jackc/pgx/v5"]
    version = "v5.7.2"
    hash = "sha256-FEh0GwrkTlFPZiqT6m3jYg5OV62/LHs/otMQuJfcMNw="
  [mod."github.com/klauspost/cpuid/v2"]
    version = "v2.2.9"
    hash = "sha256-6UnDBLqlTsKVeZNl5snKQiEBb8xGK5yyg2eZBg7QHLs="
  [mod."github.com/leodido/go-urn"]
    version = "v1.4.0"
    hash = "sha256-Q6kplWkY37Tzy6GOme3Wut40jFK4Izun+ij/BJvcEu0="
  [mod."github.com/masslbs/go-pgmmr"]
    version = "v0.0.0-20250206120136-b5495a477745"
    hash = "sha256-9Uq7Ie9e5acFKd+3TJZ0lhMOJgn2qlsH6VmrF3HbYaI="
  [mod."github.com/minio/sha256-simd"]
    version = "v1.0.1"
    hash = "sha256-4hfGDIQaWq8fvtGzHDhoK9v2IocXnJY7OAL6saMJbmA="
  [mod."github.com/mmcloughlin/addchain"]
    version = "v0.4.0"
    hash = "sha256-zSWSSUElCVFH5mydFlF2mzn4Wsm1WHASRxQ5TKa+To8="
  [mod."github.com/mr-tron/base58"]
    version = "v1.2.0"
    hash = "sha256-8FzMu3kHUbBX10pUdtGf59Ag7BNupx8ZHeUaodR1/Vk="
  [mod."github.com/multiformats/go-base32"]
    version = "v0.1.0"
    hash = "sha256-O2IM7FB+Y9MkDdZztyQL5F8oEnmON2Yew7XkotQziio="
  [mod."github.com/multiformats/go-base36"]
    version = "v0.2.0"
    hash = "sha256-GKNnAGA0Lb39BDGYBm1ieKdXmho8Pu7ouyfVPXvV0PE="
  [mod."github.com/multiformats/go-multibase"]
    version = "v0.2.0"
    hash = "sha256-w+hp6u5bWyd34qe0CX+bq487ADqq6SgRR/JuqRB578s="
  [mod."github.com/multiformats/go-multihash"]
    version = "v0.2.3"
    hash = "sha256-zqIIE5jMFzm+qhUrouSF+WdXGeHUEYIQvVnKWWU6mRs="
  [mod."github.com/multiformats/go-varint"]
    version = "v0.0.7"
    hash = "sha256-To3Uuv7uSUJEr5OTwxE1LEIpA62xY3M/KKMNlscHmlA="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/spaolacci/murmur3"]
    version = "v1.1.0"
    hash = "sha256-RWD4PPrlAsZZ8Xy356MBxpj+/NZI7w2XOU14Ob7/Y9M="
  [mod."github.com/stretchr/testify"]
    version = "v1.9.0"
    hash = "sha256-uUp/On+1nK+lARkTVtb5RxlW15zxtw2kaAFuIASA+J0="
  [mod."github.com/supranational/blst"]
    version = "v0.3.13"
    hash = "sha256-VrhbZyotNgVubxSFJH+KH2KOpApGz1PHgC0NFDmqRF0="
  [mod."github.com/x448/float16"]
    version = "v0.8.4"
    hash = "sha256-VKzMTMS9pIB/cwe17xPftCSK9Mf4Y6EuBEJlB4by5mE="
  [mod."golang.org/x/crypto"]
    version = "v0.32.0"
    hash = "sha256-4l8XyVfpunL7d03otqfx3ouG3qkSF+LT7VuH1K3oo2I="
  [mod."golang.org/x/net"]
    version = "v0.34.0"
    hash = "sha256-AZOLY4MUNxxDw5ZQtO9dmY/YRo1gFW87YvpX/eLTy4Q="
  [mod."golang.org/x/sync"]
    version = "v0.11.0"
    hash = "sha256-5ZBfDJvNaUBM4Vhk0fgYblCGL3eBxiJL85nIE8LiKl0="
  [mod."golang.org/x/sys"]
    version = "v0.29.0"
    hash = "sha256-qfsodJQ1H1CBI8yQWOvsXJgY5qHmiuw566HrrIseYHI="
  [mod."golang.org/x/text"]
    version = "v0.22.0"
    hash = "sha256-kUwLNFk9K/YuWmO5/u2IshrmhT2CCuk+mAShSlTTeZo="
  [mod."google.golang.org/protobuf"]
    version = "v1.34.2"
    hash = "sha256-nMTlrDEE2dbpWz50eQMPBQXCyQh4IdjrTIccaU0F3m0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."lukechampine.com/blake3"]
    version = "v1.3.0"
    hash = "sha256-H7ljr3coQkiNKPvn1fWm7wADu/n/PhBefTKn8UF1Wkg="
  [mod."rsc.io/tmplfunc"]
    version = "v0.0.3"
    hash = "sha256-Kii+7DxaSzzn2NphVcEk0W42TXMBFINtm3+B2t7e0cc="
