// SPDX-FileCopyrightText: 2023 - 2025 Mass Labs
//
// SPDX-License-Identifier: MIT

// Generated from network-schema/envelope.proto at version v4

// This file defines the transport protocol between relays and clients.
// It's main purpose is transfer of events of the higher application levels.
// It is orthogonal to the shop registry and other smart contracts.
//
// Messages must be prefixed with their acompanying encoding number
// as a single byte. encoding.txt defines the number for each message.
//
// Furthermore, we expect only one message per write/binary frame.
// This means no buffering of multiple messages into a single write.
// The protocol offers repeated fields where appropriate for higher throughput.
// A suggested transport is WebSocket over HTTPS but the protocol is
// agnostic, as long as it can handle binary data and keeps the framing intact.
// This design, specifically the push from the relay to client, assumes
// the transport does not offer backpressure. No further pushes are sent
// until they are acknowledged by the client.
//
// For upgrades there exists a VERSION file in the root of the repository.
// The VERSION is a single unsigned integer, incremented for each change.
// The client and relay must agree on the VERSION before starting the protocol.
// In the case of WebSocket, the VERSION can be compared via the URL.
// The relay must close the connection if the VERSION isn't supported.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: envelope.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope is how client and server exchange requests and responses.
type Envelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId *RequestId             `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*Envelope_Response
	//	*Envelope_PatchSetWriteRequest
	//	*Envelope_SubscriptionRequest
	//	*Envelope_SubscriptionCancelRequest
	//	*Envelope_SubscriptionPushRequest
	//	*Envelope_SyncStatusRequest
	//	*Envelope_PingRequest
	//	*Envelope_GetBlobUploadUrlRequest
	//	*Envelope_AuthRequest
	//	*Envelope_ChallengeSolutionRequest
	Message       IsEnvelope_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetRequestId() *RequestId {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *Envelope) GetMessage() IsEnvelope_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Envelope) GetResponse() *Envelope_GenericResponse {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *Envelope) GetPatchSetWriteRequest() *PatchSetWriteRequest {
	if x != nil {
		if x, ok := x.Message.(*Envelope_PatchSetWriteRequest); ok {
			return x.PatchSetWriteRequest
		}
	}
	return nil
}

func (x *Envelope) GetSubscriptionRequest() *SubscriptionRequest {
	if x != nil {
		if x, ok := x.Message.(*Envelope_SubscriptionRequest); ok {
			return x.SubscriptionRequest
		}
	}
	return nil
}

func (x *Envelope) GetSubscriptionCancelRequest() *SubscriptionCancelRequest {
	if x != nil {
		if x, ok := x.Message.(*Envelope_SubscriptionCancelRequest); ok {
			return x.SubscriptionCancelRequest
		}
	}
	return nil
}

func (x *Envelope) GetSubscriptionPushRequest() *SubscriptionPushRequest {
	if x != nil {
		if x, ok := x.Message.(*Envelope_SubscriptionPushRequest); ok {
			return x.SubscriptionPushRequest
		}
	}
	return nil
}

func (x *Envelope) GetSyncStatusRequest() *SyncStatusRequest {
	if x != nil {
		if x, ok := x.Message.(*Envelope_SyncStatusRequest); ok {
			return x.SyncStatusRequest
		}
	}
	return nil
}

func (x *Envelope) GetPingRequest() *PingRequest {
	if x != nil {
		if x, ok := x.Message.(*Envelope_PingRequest); ok {
			return x.PingRequest
		}
	}
	return nil
}

func (x *Envelope) GetGetBlobUploadUrlRequest() *GetBlobUploadURLRequest {
	if x != nil {
		if x, ok := x.Message.(*Envelope_GetBlobUploadUrlRequest); ok {
			return x.GetBlobUploadUrlRequest
		}
	}
	return nil
}

func (x *Envelope) GetAuthRequest() *AuthenticateRequest {
	if x != nil {
		if x, ok := x.Message.(*Envelope_AuthRequest); ok {
			return x.AuthRequest
		}
	}
	return nil
}

func (x *Envelope) GetChallengeSolutionRequest() *ChallengeSolvedRequest {
	if x != nil {
		if x, ok := x.Message.(*Envelope_ChallengeSolutionRequest); ok {
			return x.ChallengeSolutionRequest
		}
	}
	return nil
}

type IsEnvelope_Message interface {
	IsEnvelope_Message()
}

type Envelope_Response struct {
	Response *Envelope_GenericResponse `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

type Envelope_PatchSetWriteRequest struct {
	// write operation
	PatchSetWriteRequest *PatchSetWriteRequest `protobuf:"bytes,3,opt,name=patch_set_write_request,json=patchSetWriteRequest,proto3,oneof"`
}

type Envelope_SubscriptionRequest struct {
	// subscriptions
	SubscriptionRequest *SubscriptionRequest `protobuf:"bytes,4,opt,name=subscription_request,json=subscriptionRequest,proto3,oneof"`
}

type Envelope_SubscriptionCancelRequest struct {
	SubscriptionCancelRequest *SubscriptionCancelRequest `protobuf:"bytes,5,opt,name=subscription_cancel_request,json=subscriptionCancelRequest,proto3,oneof"`
}

type Envelope_SubscriptionPushRequest struct {
	SubscriptionPushRequest *SubscriptionPushRequest `protobuf:"bytes,6,opt,name=subscription_push_request,json=subscriptionPushRequest,proto3,oneof"`
}

type Envelope_SyncStatusRequest struct {
	// sync state information
	SyncStatusRequest *SyncStatusRequest `protobuf:"bytes,7,opt,name=sync_status_request,json=syncStatusRequest,proto3,oneof"`
}

type Envelope_PingRequest struct {
	PingRequest *PingRequest `protobuf:"bytes,8,opt,name=ping_request,json=pingRequest,proto3,oneof"`
}

type Envelope_GetBlobUploadUrlRequest struct {
	// shop requests
	GetBlobUploadUrlRequest *GetBlobUploadURLRequest `protobuf:"bytes,9,opt,name=get_blob_upload_url_request,json=getBlobUploadUrlRequest,proto3,oneof"`
}

type Envelope_AuthRequest struct {
	// authentication messages
	AuthRequest *AuthenticateRequest `protobuf:"bytes,10,opt,name=auth_request,json=authRequest,proto3,oneof"`
}

type Envelope_ChallengeSolutionRequest struct {
	ChallengeSolutionRequest *ChallengeSolvedRequest `protobuf:"bytes,11,opt,name=challenge_solution_request,json=challengeSolutionRequest,proto3,oneof"`
}

func (*Envelope_Response) IsEnvelope_Message() {}

func (*Envelope_PatchSetWriteRequest) IsEnvelope_Message() {}

func (*Envelope_SubscriptionRequest) IsEnvelope_Message() {}

func (*Envelope_SubscriptionCancelRequest) IsEnvelope_Message() {}

func (*Envelope_SubscriptionPushRequest) IsEnvelope_Message() {}

func (*Envelope_SyncStatusRequest) IsEnvelope_Message() {}

func (*Envelope_PingRequest) IsEnvelope_Message() {}

func (*Envelope_GetBlobUploadUrlRequest) IsEnvelope_Message() {}

func (*Envelope_AuthRequest) IsEnvelope_Message() {}

func (*Envelope_ChallengeSolutionRequest) IsEnvelope_Message() {}

type Envelope_GenericResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*Envelope_GenericResponse_Error
	//	*Envelope_GenericResponse_Payload
	Response      isEnvelope_GenericResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope_GenericResponse) Reset() {
	*x = Envelope_GenericResponse{}
	mi := &file_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope_GenericResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope_GenericResponse) ProtoMessage() {}

func (x *Envelope_GenericResponse) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope_GenericResponse.ProtoReflect.Descriptor instead.
func (*Envelope_GenericResponse) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Envelope_GenericResponse) GetResponse() isEnvelope_GenericResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *Envelope_GenericResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*Envelope_GenericResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Envelope_GenericResponse) GetPayload() []byte {
	if x != nil {
		if x, ok := x.Response.(*Envelope_GenericResponse_Payload); ok {
			return x.Payload
		}
	}
	return nil
}

type isEnvelope_GenericResponse_Response interface {
	isEnvelope_GenericResponse_Response()
}

type Envelope_GenericResponse_Error struct {
	Error *Error `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

type Envelope_GenericResponse_Payload struct {
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3,oneof"`
}

func (*Envelope_GenericResponse_Error) isEnvelope_GenericResponse_Response() {}

func (*Envelope_GenericResponse_Payload) isEnvelope_GenericResponse_Response() {}

var File_envelope_proto protoreflect.FileDescriptor

const file_envelope_proto_rawDesc = "" +
	"\n" +
	"\x0eenvelope.proto\x12\vmarket.mass\x1a\x14authentication.proto\x1a\x10base_types.proto\x1a\verror.proto\x1a\x13shop_requests.proto\x1a\x12subscription.proto\x1a\x0ftransport.proto\"\x9c\b\n" +
	"\bEnvelope\x125\n" +
	"\n" +
	"request_id\x18\x01 \x01(\v2\x16.market.mass.RequestIdR\trequestId\x12C\n" +
	"\bresponse\x18\x02 \x01(\v2%.market.mass.Envelope.GenericResponseH\x00R\bresponse\x12Z\n" +
	"\x17patch_set_write_request\x18\x03 \x01(\v2!.market.mass.PatchSetWriteRequestH\x00R\x14patchSetWriteRequest\x12U\n" +
	"\x14subscription_request\x18\x04 \x01(\v2 .market.mass.SubscriptionRequestH\x00R\x13subscriptionRequest\x12h\n" +
	"\x1bsubscription_cancel_request\x18\x05 \x01(\v2&.market.mass.SubscriptionCancelRequestH\x00R\x19subscriptionCancelRequest\x12b\n" +
	"\x19subscription_push_request\x18\x06 \x01(\v2$.market.mass.SubscriptionPushRequestH\x00R\x17subscriptionPushRequest\x12P\n" +
	"\x13sync_status_request\x18\a \x01(\v2\x1e.market.mass.SyncStatusRequestH\x00R\x11syncStatusRequest\x12=\n" +
	"\fping_request\x18\b \x01(\v2\x18.market.mass.PingRequestH\x00R\vpingRequest\x12d\n" +
	"\x1bget_blob_upload_url_request\x18\t \x01(\v2$.market.mass.GetBlobUploadURLRequestH\x00R\x17getBlobUploadUrlRequest\x12E\n" +
	"\fauth_request\x18\n" +
	" \x01(\v2 .market.mass.AuthenticateRequestH\x00R\vauthRequest\x12c\n" +
	"\x1achallenge_solution_request\x18\v \x01(\v2#.market.mass.ChallengeSolvedRequestH\x00R\x18challengeSolutionRequest\x1ae\n" +
	"\x0fGenericResponse\x12*\n" +
	"\x05error\x18\x01 \x01(\v2\x12.market.mass.ErrorH\x00R\x05error\x12\x1a\n" +
	"\apayload\x18\x02 \x01(\fH\x00R\apayloadB\n" +
	"\n" +
	"\bresponseB\t\n" +
	"\amessageb\x06proto3"

var (
	file_envelope_proto_rawDescOnce sync.Once
	file_envelope_proto_rawDescData []byte
)

func file_envelope_proto_rawDescGZIP() []byte {
	file_envelope_proto_rawDescOnce.Do(func() {
		file_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)))
	})
	return file_envelope_proto_rawDescData
}

var file_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_envelope_proto_goTypes = []any{
	(*Envelope)(nil),                  // 0: market.mass.Envelope
	(*Envelope_GenericResponse)(nil),  // 1: market.mass.Envelope.GenericResponse
	(*RequestId)(nil),                 // 2: market.mass.RequestId
	(*PatchSetWriteRequest)(nil),      // 3: market.mass.PatchSetWriteRequest
	(*SubscriptionRequest)(nil),       // 4: market.mass.SubscriptionRequest
	(*SubscriptionCancelRequest)(nil), // 5: market.mass.SubscriptionCancelRequest
	(*SubscriptionPushRequest)(nil),   // 6: market.mass.SubscriptionPushRequest
	(*SyncStatusRequest)(nil),         // 7: market.mass.SyncStatusRequest
	(*PingRequest)(nil),               // 8: market.mass.PingRequest
	(*GetBlobUploadURLRequest)(nil),   // 9: market.mass.GetBlobUploadURLRequest
	(*AuthenticateRequest)(nil),       // 10: market.mass.AuthenticateRequest
	(*ChallengeSolvedRequest)(nil),    // 11: market.mass.ChallengeSolvedRequest
	(*Error)(nil),                     // 12: market.mass.Error
}
var file_envelope_proto_depIdxs = []int32{
	2,  // 0: market.mass.Envelope.request_id:type_name -> market.mass.RequestId
	1,  // 1: market.mass.Envelope.response:type_name -> market.mass.Envelope.GenericResponse
	3,  // 2: market.mass.Envelope.patch_set_write_request:type_name -> market.mass.PatchSetWriteRequest
	4,  // 3: market.mass.Envelope.subscription_request:type_name -> market.mass.SubscriptionRequest
	5,  // 4: market.mass.Envelope.subscription_cancel_request:type_name -> market.mass.SubscriptionCancelRequest
	6,  // 5: market.mass.Envelope.subscription_push_request:type_name -> market.mass.SubscriptionPushRequest
	7,  // 6: market.mass.Envelope.sync_status_request:type_name -> market.mass.SyncStatusRequest
	8,  // 7: market.mass.Envelope.ping_request:type_name -> market.mass.PingRequest
	9,  // 8: market.mass.Envelope.get_blob_upload_url_request:type_name -> market.mass.GetBlobUploadURLRequest
	10, // 9: market.mass.Envelope.auth_request:type_name -> market.mass.AuthenticateRequest
	11, // 10: market.mass.Envelope.challenge_solution_request:type_name -> market.mass.ChallengeSolvedRequest
	12, // 11: market.mass.Envelope.GenericResponse.error:type_name -> market.mass.Error
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_envelope_proto_init() }
func file_envelope_proto_init() {
	if File_envelope_proto != nil {
		return
	}
	file_authentication_proto_init()
	file_base_types_proto_init()
	file_error_proto_init()
	file_shop_requests_proto_init()
	file_subscription_proto_init()
	file_transport_proto_init()
	file_envelope_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Response)(nil),
		(*Envelope_PatchSetWriteRequest)(nil),
		(*Envelope_SubscriptionRequest)(nil),
		(*Envelope_SubscriptionCancelRequest)(nil),
		(*Envelope_SubscriptionPushRequest)(nil),
		(*Envelope_SyncStatusRequest)(nil),
		(*Envelope_PingRequest)(nil),
		(*Envelope_GetBlobUploadUrlRequest)(nil),
		(*Envelope_AuthRequest)(nil),
		(*Envelope_ChallengeSolutionRequest)(nil),
	}
	file_envelope_proto_msgTypes[1].OneofWrappers = []any{
		(*Envelope_GenericResponse_Error)(nil),
		(*Envelope_GenericResponse_Payload)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envelope_proto_goTypes,
		DependencyIndexes: file_envelope_proto_depIdxs,
		MessageInfos:      file_envelope_proto_msgTypes,
	}.Build()
	File_envelope_proto = out.File
	file_envelope_proto_goTypes = nil
	file_envelope_proto_depIdxs = nil
}
