// SPDX-FileCopyrightText: 2024 - 2025 Mass Labs
//
// SPDX-License-Identifier: MIT

// Generated from network-schema/error.proto at version v4

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: error.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCodes int32

const (
	ErrorCodes_UNSPECIFIED                  ErrorCodes = 0
	ErrorCodes_NOT_FOUND                    ErrorCodes = 1
	ErrorCodes_INVALID                      ErrorCodes = 2
	ErrorCodes_NOT_AUTHENTICATED            ErrorCodes = 3
	ErrorCodes_ALREADY_AUTHENTICATED        ErrorCodes = 4
	ErrorCodes_ALREADY_CONNECTED            ErrorCodes = 5
	ErrorCodes_TOO_MANY_CONCURRENT_REQUESTS ErrorCodes = 6
	ErrorCodes_UNLINKED_KEYCARD             ErrorCodes = 7
	ErrorCodes_MINIMUM_VERSION_NOT_REACHED  ErrorCodes = 8
	ErrorCodes_OUT_OF_STOCK                 ErrorCodes = 9
	// use to signal randmom/simulated errors
	ErrorCodes_SIMULATED ErrorCodes = 10
	// used to cleanly stop sending events from the relay to the client
	ErrorCodes_CLOSE_SUBSCRIPTION ErrorCodes = 11
)

// Enum value maps for ErrorCodes.
var (
	ErrorCodes_name = map[int32]string{
		0:  "ERROR_CODES_UNSPECIFIED",
		1:  "ERROR_CODES_NOT_FOUND",
		2:  "ERROR_CODES_INVALID",
		3:  "ERROR_CODES_NOT_AUTHENTICATED",
		4:  "ERROR_CODES_ALREADY_AUTHENTICATED",
		5:  "ERROR_CODES_ALREADY_CONNECTED",
		6:  "ERROR_CODES_TOO_MANY_CONCURRENT_REQUESTS",
		7:  "ERROR_CODES_UNLINKED_KEYCARD",
		8:  "ERROR_CODES_MINIMUM_VERSION_NOT_REACHED",
		9:  "ERROR_CODES_OUT_OF_STOCK",
		10: "ERROR_CODES_SIMULATED",
		11: "ERROR_CODES_CLOSE_SUBSCRIPTION",
	}
	ErrorCodes_value = map[string]int32{
		"ERROR_CODES_UNSPECIFIED":                  0,
		"ERROR_CODES_NOT_FOUND":                    1,
		"ERROR_CODES_INVALID":                      2,
		"ERROR_CODES_NOT_AUTHENTICATED":            3,
		"ERROR_CODES_ALREADY_AUTHENTICATED":        4,
		"ERROR_CODES_ALREADY_CONNECTED":            5,
		"ERROR_CODES_TOO_MANY_CONCURRENT_REQUESTS": 6,
		"ERROR_CODES_UNLINKED_KEYCARD":             7,
		"ERROR_CODES_MINIMUM_VERSION_NOT_REACHED":  8,
		"ERROR_CODES_OUT_OF_STOCK":                 9,
		"ERROR_CODES_SIMULATED":                    10,
		"ERROR_CODES_CLOSE_SUBSCRIPTION":           11,
	}
)

func (x ErrorCodes) Enum() *ErrorCodes {
	p := new(ErrorCodes)
	*p = x
	return p
}

func (x ErrorCodes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCodes) Descriptor() protoreflect.EnumDescriptor {
	return file_error_proto_enumTypes[0].Descriptor()
}

func (ErrorCodes) Type() protoreflect.EnumType {
	return &file_error_proto_enumTypes[0]
}

func (x ErrorCodes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCodes.Descriptor instead.
func (ErrorCodes) EnumDescriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{0}
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCodes             `protobuf:"varint,1,opt,name=code,proto3,enum=market.mass.ErrorCodes" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() ErrorCodes {
	if x != nil {
		return x.Code
	}
	return ErrorCodes_UNSPECIFIED
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_error_proto protoreflect.FileDescriptor

const file_error_proto_rawDesc = "" +
	"\n" +
	"\verror.proto\x12\vmarket.mass\"N\n" +
	"\x05Error\x12+\n" +
	"\x04code\x18\x01 \x01(\x0e2\x17.market.mass.ErrorCodesR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xa4\x03\n" +
	"\n" +
	"ErrorCodes\x12\x1b\n" +
	"\x17ERROR_CODES_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ERROR_CODES_NOT_FOUND\x10\x01\x12\x17\n" +
	"\x13ERROR_CODES_INVALID\x10\x02\x12!\n" +
	"\x1dERROR_CODES_NOT_AUTHENTICATED\x10\x03\x12%\n" +
	"!ERROR_CODES_ALREADY_AUTHENTICATED\x10\x04\x12!\n" +
	"\x1dERROR_CODES_ALREADY_CONNECTED\x10\x05\x12,\n" +
	"(ERROR_CODES_TOO_MANY_CONCURRENT_REQUESTS\x10\x06\x12 \n" +
	"\x1cERROR_CODES_UNLINKED_KEYCARD\x10\a\x12+\n" +
	"'ERROR_CODES_MINIMUM_VERSION_NOT_REACHED\x10\b\x12\x1c\n" +
	"\x18ERROR_CODES_OUT_OF_STOCK\x10\t\x12\x19\n" +
	"\x15ERROR_CODES_SIMULATED\x10\n" +
	"\x12\"\n" +
	"\x1eERROR_CODES_CLOSE_SUBSCRIPTION\x10\vb\x06proto3"

var (
	file_error_proto_rawDescOnce sync.Once
	file_error_proto_rawDescData []byte
)

func file_error_proto_rawDescGZIP() []byte {
	file_error_proto_rawDescOnce.Do(func() {
		file_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_error_proto_rawDesc), len(file_error_proto_rawDesc)))
	})
	return file_error_proto_rawDescData
}

var file_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_error_proto_goTypes = []any{
	(ErrorCodes)(0), // 0: market.mass.ErrorCodes
	(*Error)(nil),   // 1: market.mass.Error
}
var file_error_proto_depIdxs = []int32{
	0, // 0: market.mass.Error.code:type_name -> market.mass.ErrorCodes
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_error_proto_init() }
func file_error_proto_init() {
	if File_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_error_proto_rawDesc), len(file_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_error_proto_goTypes,
		DependencyIndexes: file_error_proto_depIdxs,
		EnumInfos:         file_error_proto_enumTypes,
		MessageInfos:      file_error_proto_msgTypes,
	}.Build()
	File_error_proto = out.File
	file_error_proto_goTypes = nil
	file_error_proto_depIdxs = nil
}
