// SPDX-FileCopyrightText: 2025 Mass Labs
//
// SPDX-License-Identifier: MIT

// Code generated by "stringer -output gen_order_payment_state_string.go -trimprefix OrderPaymentState -type OrderPaymentState ."; DO NOT EDIT.

package objects

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OrderPaymentStateUnspecified-0]
	_ = x[OrderPaymentStateCanceled-1]
	_ = x[OrderPaymentStateOpen-2]
	_ = x[OrderPaymentStateLocked-3]
	_ = x[OrderPaymentStatePaymentChosen-4]
	_ = x[OrderPaymentStateUnpaid-5]
	_ = x[OrderPaymentStateUnpaidExpired-6]
	_ = x[OrderPaymentStatePaid-7]
	_ = x[OrderPaymentStatePaidLate-8]
	_ = x[maxOrderPaymentState-9]
}

const _OrderPaymentState_name = "UnspecifiedCanceledOpenLockedPaymentChosenUnpaidUnpaidExpiredPaidPaidLatemaxOrderPaymentState"

var _OrderPaymentState_index = [...]uint8{0, 11, 19, 23, 29, 42, 48, 61, 65, 73, 93}

func (i OrderPaymentState) String() string {
	if i >= OrderPaymentState(len(_OrderPaymentState_index)-1) {
		return "OrderPaymentState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OrderPaymentState_name[_OrderPaymentState_index[i]:_OrderPaymentState_index[i+1]]
}
