# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\x12\x08tutorial\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"/\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\"z\n\x05Robot\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12)\n\x08\x66\x65\x61tures\x18\x03 \x03(\x0b\x32\x17.tutorial.Robot.Feature\x1a,\n\x07\x46\x65\x61ture\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\x7f\n\x04Task\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12,\n\x08\x64ue_date\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12%\n\x07\x64one_by\x18\x04 \x01(\x0b\x32\x14.google.protobuf.AnyB<Z:github.com/protocolbuffers/protobuf/examples/go/tutorialpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:github.com/protocolbuffers/protobuf/examples/go/tutorialpb'
  _globals['_PERSON']._serialized_start=86
  _globals['_PERSON']._serialized_end=133
  _globals['_ROBOT']._serialized_start=135
  _globals['_ROBOT']._serialized_end=257
  _globals['_ROBOT_FEATURE']._serialized_start=213
  _globals['_ROBOT_FEATURE']._serialized_end=257
  _globals['_TASK']._serialized_start=259
  _globals['_TASK']._serialized_end=386
# @@protoc_insertion_point(module_scope)
